name: Split repositories

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
`
````runs-on: ubuntu-latest
    uses: actions/checkout@v3
  
    steps:
    
    - name: prepare git
      env: 
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: git config --global url."https://bigyao@139.com:${TOKEN}@github.com".insteadOf "https://github.com"
      
    - name: split repositories
      run: chmod +x ./bin/split-linux.sh && ./bin/split-linux.sh
